# set server port
server:
  port: 8888
  context-path: /

spring:
  datasource: # set database config
    url: jdbc:mysql://localhost:3306/estate_agent?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: normal
    password: normal
    driver-class-name: com.mysql.jdbc.Driver
  jpa: # set jpa
    database: MYSQL # specify ths DBMS
    show-sql: true # show or not log for each sql query
    hibernate:
      ddl-auto: update # Hibernate ddl auto(create, create-drop, update)
      naming: # naming strategy
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: # stripped before adding them to entity manager
        dialect: org.hibernate.dialect.MySQL5Dialect
  aop: #设置aop,aop依赖添加后默认是启用的
    proxy-target-class: true

  # Thymeleaf view template config
  # disable cache for dev
  thymeleaf:
    cache: false
    encoding: UTF-8
    # 设置LEGACYHTML5 并添加依赖 可以使thymeleaf不严格模式
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /**

#  mvc:
#    view: # 默认前后缀
#      prefix: /
#      suffix: .html
#    static-path-pattern: /**
#logging: #相对位置，根目录
#  path: var/log
# 日志级别 TRACE < DEBUG < INFO < WARN < ERROR < FATAL
#logging: # 配置日志文件的配置方式  logback-spring.* 也为spring的默认命名规则
#  config: logback-spring.xml




